version: "3.7"
services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: 12345

    restaurantsapi:
        image: "restaurantsapi"
        container_name: restaurantsapi-container
        restart: always
        ports:
            - "5001:5001"
        depends_on:
            - mongo
    restaurantsclient:
        image: "restaurantsclient"
        container_name: restaurantsclient-container
        restart: always
        ports:
            - "8081:8081"
        depends_on: 
            - restaurantsapi